### ISSUE TITLE
transpile / refactor code into es5

### ISSUE THREAD

**Issue by antony** [Rich-Harris/shimport#34]
Since version 2.0.0 this library has started shipping code which includes const and let which have dubious support in legacy browsers, but also arrow functions which cause legacy browsers such as IE11 to simply break.

Since this library isn't usually transpiled by those who depend on it due to the way it is used, this means that IE support is completely broken, since 2.x.

I believe the solution to this would be to transpile the JS before publishing, into a syntax which works on older browsers.

**Comment by benmccann** [comment]
I think this was previously done by `@rollup/plugin-typescript` and was probably lost when the config switched to `@rollup/plugin-sucrase`

**Comment by antony** [comment]
Looks like the official word from the sucrase author is that it is designed to target modern browsers and node versions, and does not have any support to ES5, so I think the best way is as ben mentioned above, to switch back to the TypeScript compiler.

**Comment by ansballard** [comment]
instead of transpiling to es5 for all users, would it be enough to add another output and reference it from the `browser` field in package.json? Made a quick n dirty version [here](https://github.com/Rich-Harris/shimport/compare/master...ansballard:typescript?expand=1), just adds typescript, an extra output from rollup that uses it and targets es5, and adds the `browser` field to reference it. It is nice to be able to keep libraries from shipping es5 by default, since at this point support for es2015+ is so wide.

**Comment by benmccann** [comment]
But this library would only get shipped for users if legacy browsers, right? So I'm not sure I understand the point of that
